/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package contoh;

public class App {
    

    public static void main(String[] args) {
        Customer customer1 = new Customer("Eko", "Palembang");
        Order order1 = new Order("baju", 2500, 2);
        customer1.order(order1);

        Customer customer2 = new Customer("Nindy", "Yogyakarta");
        Order order2 = new Order("baju", 2500, 2);
        customer2.order(order2);
    }



}
