/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

public class App {
    // public String getGreeting() {
    //     return "Hello world.";
    // }

    // public static void main(String[] args) {
    //     System.out.println(new App().getGreeting());
    // }
    public static void main(String[] args) {
        Bicycle bike1 = new Bicycle();
        Bicycle bike2 = new Bicycle();

        bike1.changeCadence(50);
        bike1.speedUp(10);
        bike1.changeGear(2);
        bike1.printStates();

        bike2.changeCadence(50);
        bike2.speedUp(10);
        bike2.changeGear(40);
        bike2.changeCadence(20);
        bike2.speedUp(10);
        bike2.changeGear(3);
        bike2.printStates();
    }
}

